spring:
datasource:
url: jdbc:mysql://my-rds-instance.cnwom4kocpo9.ap-northeast-2.rds.amazonaws.com:3306/my_rds_name?useSSL=false&serverTimezone=UTC
username: admin
password: kang020511
jpa:
hibernate:
ddl-auto: update
show-sql: true
